{
  pkgs ? import <nixpkgs> {
    config = {
      permittedInsecurePackages = [
        "python3.13-ecdsa-0.19.2"
        "freeimage-unstable-2021-11-01"
        "freeimage-3.18.0-unstable-2024-04-18"
      ];
    };
    overlays = [
      # Force Protobuf 31.1 globally to match dependencies and avoid ABI hell
      (final: prev: {
        protobuf = prev.protobuf_31;
      })
      (import (fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz"))
      (final: prev: import (
        let src = fetchTarball "https://github.com/SilverLuke/gazebo-sim-overlay/archive/pr-gazebo-10-support.tar.gz";
        in "${src}/pkgs"
      ) { 
        pkgs = final;
      })
    ];
  },
}:

let
  # Fetch west2nix from GitHub
  west2nix = pkgs.callPackage (pkgs.fetchFromGitHub {
    owner = "adisbladis";
    repo = "west2nix";
    rev = "f84670d66f881d9340b7d7626fbfe499438c134b";
    hash = "sha256-D6iH0d67AmlB7k3QIjUvNo7NafzWy03HOHV5o4w251s=";
  }) { callPackage = pkgs.callPackage; python3 = pkgs.python3; };

  # Check for projects.nix generated by 'west2nix convert'
  projects = if builtins.pathExists ./projects.nix then import ./projects.nix else null;

  hookContent = if projects != null
    then west2nix.mkWest2nixHook { manifest = projects; }
    else "";

  # Gazebo Jetty (10) from overlay
  gz-jetty = pkgs.gz-jetty;

  # A comprehensive Python environment for Zephyr development
  pythonEnv = pkgs.python3.withPackages (
    ps: with ps; [
      anytree canopen intelhex jsonschema packaging patool psutil pyelftools pykwalify
      pylink-square pyserial pyyaml requests reuse semver setuptools tqdm west wheel
      colorama ply coverage pytest mypy junitparser python-dotenv protobuf
      pyocd tabulate natsort cbor python-can spdx-tools
      tkinter ecdsa
    ]
  );

in
pkgs.mkShell {
  nativeBuildInputs = with pkgs; [
    protobuf rerun gz-jetty uv libuuid util-linux.dev tinyxml-2 zeromq cppzmq libsodium
    SDL2 gtk4.dev glib.dev cairo.dev pango.dev gdk-pixbuf.dev graphene.dev libadwaita
    # esptool 5.x: required by Zephyr CMake (>= 5.0.2). If CH343 auto-reset
    # breaks, use FLASH_BEFORE=no-reset and manually press BOOT+EN.
    pkgs.esptool
    (rust-bin.stable.latest.default.override { extensions = [ "rust-src" "rust-analyzer" "clippy" "rustfmt" ]; }) ccache cmake dfu-util dtc file gcc gcovr git
    gperf libusb1 ncurses ninja pkg-config unzip wget which xz pythonEnv west2nix.west2nix
    mesa-demos xvfb-run imagemagick xorg-server rsyslog gnumake
    
    # Critical for Qt6/Wayland/Ogre2 EGL
    libGL
    libglvnd
    mesa
    wayland
    vulkan-loader
  ];

  shellHook = ''
    echo "--- HomeRobot (Zephyr + Rust) Nix Environment (Gazebo Jetty 10) ---"
    
    export PYTHONPATH="${gz-jetty}/lib/python:$PYTHONPATH"
    
    # --- Robust OpenGL/EGL Environment for NixOS ---
    export LD_LIBRARY_PATH="${pkgs.lib.makeLibraryPath [ pkgs.libglvnd pkgs.vulkan-loader pkgs.libGL pkgs.gtk4 pkgs.glib pkgs.graphene pkgs.pango pkgs.cairo pkgs.gdk-pixbuf pkgs.libadwaita pkgs.SDL2 ]}:${gz-jetty}/lib:$LD_LIBRARY_PATH"
    export LD_LIBRARY_PATH="/run/opengl-driver/lib:/run/opengl-driver-32/lib:$LD_LIBRARY_PATH"
    
    export LIBGL_DRIVERS_PATH="/run/opengl-driver/lib/dri"
    export __EGL_VENDOR_LIBRARY_FILENAMES="/run/opengl-driver/share/glvnd/egl_vendor.d/50_mesa.json"
    
    [ -d "$LIBGL_DRIVERS_PATH" ] || export LIBGL_DRIVERS_PATH="${pkgs.mesa}/lib/dri"
    [ -f "$__EGL_VENDOR_LIBRARY_FILENAMES" ] || export __EGL_VENDOR_LIBRARY_FILENAMES="${pkgs.mesa}/share/glvnd/egl_vendor.d/50_mesa.json"

    export GZ_PARTITION=homerobot_sim
    export GZ_IP=127.0.0.1

    # Fix QT_PLUGIN_PATH and QML_IMPORT_PATH for Gazebo Jetty (Qt 6)
    GZ_QT_PLUGIN_PATH=""
    GZ_QML_IMPORT_PATH=""
    for dep in $(nix-store -qR "${gz-jetty}" 2>/dev/null); do
      if [ -d "$dep/lib/qt-6/plugins" ]; then
        GZ_QT_PLUGIN_PATH="$dep/lib/qt-6/plugins:$GZ_QT_PLUGIN_PATH"
      fi
      if [ -d "$dep/lib/qt-6/qml" ]; then
        GZ_QML_IMPORT_PATH="$dep/lib/qt-6/qml:$GZ_QML_IMPORT_PATH"
      fi
    done
    
    export QT_PLUGIN_PATH="$GZ_QT_PLUGIN_PATH"
    export QML_IMPORT_PATH="$GZ_QML_IMPORT_PATH"
    export QML2_IMPORT_PATH="$GZ_QML_IMPORT_PATH"
    
    export LD_LIBRARY_PATH="/run/opengl-driver/lib:/run/opengl-driver-32/lib:$LD_LIBRARY_PATH"
    
    if [ -n "$WAYLAND_DISPLAY" ]; then
       echo "  [INFO] Wayland detected ($WAYLAND_DISPLAY). Using native Wayland/EGL stack."
       export QT_QPA_PLATFORM="xcb"
       export GDK_BACKEND="x11"
       export QT_QPA_PLATFORMTHEME="fusion"
       export XDG_SESSION_TYPE="x11"
       # export EGL_PLATFORM="surfaceless" # Allow headless DRM to work correctly
    fi

    # Ensure Ogre2 can find its plugins and Media (Hlms)
    # OGRE2_RESOURCE_PATH should point to the directory containing plugins and the Media folder
    export OGRE2_RESOURCE_PATH="${pkgs.ogre-next}/lib/OGRE-Next"
    export GZ_SIM_RESOURCE_PATH="${pkgs.ogre-next}/share/OGRE-Next/Media:$GZ_SIM_RESOURCE_PATH"
    
    # Force Ogre to find its own HLMS shaders
    export OGRE_MEDIA_PATH="${pkgs.ogre-next}/share/OGRE-Next/Media"

    if [ -d "$PWD/zephyrproject/zephyr" ]; then
      export ZEPHYR_BASE="$PWD/zephyrproject/zephyr"
    fi

    [ -f .env ] && { set -o allexport; source .env; set +o allexport; }

    export CCACHE_DIR="$PWD/.ccache"
    export PATH="${pkgs.ccache}/lib/ccache:$PATH"
    export CMAKE_C_COMPILER_LAUNCHER=ccache
    export CMAKE_CXX_COMPILER_LAUNCHER=ccache

    export GZ_SIM_RESOURCE_PATH="$PWD/simulation:$GZ_SIM_RESOURCE_PATH"

    ${hookContent}

    # --- Local Rsyslog Daemon Management ---
    mkdir -p "''$PWD/logs/rsyslog"
    mkdir -p "''$PWD/logs/remote"

    cat <<'EOF' > "''$PWD/logs/rsyslog.conf"
module(load="imudp")
input(type="imudp" port="1514")

module(load="imtcp")
input(type="imtcp" port="1514")

global(workDirectory="''$PWD/logs/rsyslog")

template(name="RemoteLogs" type="string"
  string="''$PWD/logs/remote/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%.log"
)

*.* ?RemoteLogs
*.* @127.0.0.1:5140
EOF

    # Only manage rsyslog lifecycle in interactive shells.
    # nix-direnv evaluates shellHook in a non-interactive subshell whose
    # EXIT trap fires immediately, killing the daemon on every env reload.
    if [[ ''$- == *i* ]]; then
        _HR_COUNTER="''$PWD/logs/rsyslog/shell_count"

        # Increment the shell reference counter
        _hr_n=''$(cat "''$_HR_COUNTER" 2>/dev/null || echo 0)
        echo ''$((_hr_n + 1)) > "''$_HR_COUNTER"

        # Start rsyslogd if not already running
        _HR_RUNNING=0
        if [ -f "''$PWD/logs/rsyslog/rsyslogd.pid" ]; then
            _HR_PID=''$(cat "''$PWD/logs/rsyslog/rsyslogd.pid" 2>/dev/null)
            if [ -n "''$_HR_PID" ] && kill -0 "''$_HR_PID" 2>/dev/null; then
                echo "  [INFO] Local rsyslogd is already running (PID ''$_HR_PID)."
                _HR_RUNNING=1
            fi
        fi

        if [ ''$_HR_RUNNING -eq 0 ]; then
            echo "  [INFO] Starting local Rsyslog daemon on port 1514..."
            rsyslogd -i "''$PWD/logs/rsyslog/rsyslogd.pid" -f "''$PWD/logs/rsyslog.conf"
        fi

        # On exit: decrement counter, only stop rsyslogd when last shell closes
        trap '
            _HR_COUNTER="''$PWD/logs/rsyslog/shell_count"
            _hr_n=''$(cat "''$_HR_COUNTER" 2>/dev/null || echo 1)
            _hr_n=''$((_hr_n - 1))
            [ ''$_hr_n -lt 0 ] && _hr_n=0
            echo ''$_hr_n > "''$_HR_COUNTER"
            if [ ''$_hr_n -eq 0 ]; then
                if [ -f "''$PWD/logs/rsyslog/rsyslogd.pid" ]; then
                    _HR_PID=''$(cat "''$PWD/logs/rsyslog/rsyslogd.pid" 2>/dev/null)
                    if [ -n "''$_HR_PID" ]; then
                        echo "Stopping local rsyslogd (PID ''$_HR_PID)..."
                        kill "''$_HR_PID" 2>/dev/null || true
                    fi
                fi
            fi
        ' EXIT
    fi

    echo "  [✓] Environment ready. 'west' and Gazebo Jetty are available."
    echo "  [TIP] Run simulation with: ./tools/sim_world.sh"
  '';
}
