{
  pkgs ? import <nixpkgs> {
    config = {
      permittedInsecurePackages = [
        "python3.13-ecdsa-0.19.1"
      ];
    };
  },
}:

let
  # Fetch the Gazebo Sim overlay flake and convert it for use in non-flake shell.nix
  gazebo-flake = import (fetchTarball "https://github.com/edolstra/flake-compat/archive/master.tar.gz") {
    src = fetchTarball "https://github.com/muellerbernd/gazebo-sim-overlay/archive/master.tar.gz";
  };
  gz-ionic = gazebo-flake.defaultNix.legacyPackages.${builtins.currentSystem}.gz-ionic;

  # Fetch west2nix from GitHub as in the original file
  west2nix = pkgs.callPackage (pkgs.fetchFromGitHub {
    owner = "adisbladis";
    repo = "west2nix";
    rev = "f84670d66f881d9340b7d7626fbfe499438c134b";
    hash = "sha256-D6iH0d67AmlB7k3QIjUvNo7NafzWy03HOHV5o4w251s=";
  }) { callPackage = pkgs.callPackage; python3 = pkgs.python3; };

  # Check for projects.nix generated by 'west2nix convert'
  projectsFile = ./projects.nix;
  projects = if builtins.pathExists projectsFile 
             then let p = import projectsFile; in if p != {} then p else null
             else null;

  # Only generate hook script if projects exist, but don't run it by default
  # if it causes massive fetches.
  workspaceSetup = if projects != null
    then west2nix.mkWest2nixHook { manifest = projects; }
    else "true";

  # A comprehensive Python environment for Zephyr development, using the "Nix way"
  pythonEnv = pkgs.python3.withPackages (
    ps: with ps; [
      # Base requirements from requirements-base.txt
      anytree
      canopen
      intelhex
      jsonschema
      packaging
      patool
      psutil
      pyelftools
      pykwalify
      pylink-square
      pyserial
      pyyaml
      requests
      reuse
      semver
      setuptools
      tqdm
      west
      wheel
      # Build/Test requirements
      colorama
      ply
      coverage
      pytest
      mypy
      junitparser
      python-dotenv
      protobuf
      # Runtime/Test requirements
      pyocd
      tabulate
      natsort
      cbor
      python-can
      spdx-tools
      # For menuconfig/guiconfig
      tkinter
      ecdsa
    ]
  );

in
pkgs.mkShell {
  nativeBuildInputs = with pkgs; [
    # Gazebo Sim (Ionic) from the overlay
    gz-ionic

    # System dependencies for Zephyr and Server
    SDL2
    gtk4.dev
    glib.dev
    cairo.dev
    pango.dev
    gdk-pixbuf.dev
    graphene.dev
    libadwaita
    cargo
    rustc
    ccache
    cmake
    dfu-util
    dtc
    esptool # For ESP32 flashing
    file
    gcc
    gcovr
    git
    gperf
    libusb1 # For flashing/debugging
    ncurses
    ninja
    pkg-config
    protobuf
    unzip
    wget
    which
    xz

    # The Python environment with all dependencies
    pythonEnv

    # The west2nix tool itself for managing the workspace
    west2nix.west2nix
  ];

  # Environment variables and shell logic
  shellHook = ''
    echo "--- HomeRobot (Zephyr + Rust) Nix Environment ---"
    
    # Set Gazebo Python path for the bridge
    export PYTHONPATH="${gz-ionic}/lib/python:$PYTHONPATH"
    export LD_LIBRARY_PATH="${gz-ionic}/lib:$LD_LIBRARY_PATH"
    export QT_QPA_PLATFORM=xcb
    export GZ_PARTITION=homerobot_sim
    export GZ_IP=127.0.0.1

    # Set SDK and Toolchain variables
    if [ -d "$PWD/zephyr-port/zephyr-sdk-1.0.0" ]; then
      export ZEPHYR_SDK_INSTALL_DIR="$PWD/zephyr-port/zephyr-sdk-1.0.0"
      export ZEPHYR_TOOLCHAIN_VARIANT="zephyr"
    else
      echo "  [!] WARNING: Zephyr SDK not found in ./zephyr-port/"
    fi

    # Set ZEPHYR_BASE if it exists
    if [ -d "$PWD/zephyrproject/zephyr" ]; then
      export ZEPHYR_BASE="$PWD/zephyrproject/zephyr"
    fi

    # Source .env if present
    [ -f .env ] && { set -o allexport; source .env; set +o allexport; }

    # Setup workspace alias if projects.nix exists
    if [ -f projects.nix ] && [ -n "${workspaceSetup}" ]; then
      setup_workspace_fn() { echo "Updating workspace..."; ${workspaceSetup}; }
      alias setup-workspace=setup_workspace_fn
    fi

    # Configure ccache
    export CCACHE_DIR="$PWD/.ccache"
    export PATH="${pkgs.ccache}/lib/ccache:$PATH"
    export CMAKE_C_COMPILER_LAUNCHER=ccache
    export CMAKE_CXX_COMPILER_LAUNCHER=ccache

    # Gazebo Sim Resource Path
    export GZ_SIM_RESOURCE_PATH="$PWD/simulation:$GZ_SIM_RESOURCE_PATH"

    echo "  [✓] Environment ready. 'west' and Gazebo Ionic are available."
    echo "  [TIP] Run simulation with: ./tools/start_sim.sh"
  '';
}
