# Hardware features specific to ESP32-C6 HP Core
CONFIG_PICOLIBC=y
CONFIG_FPU=n

# Bootloader (Using MCUboot)
CONFIG_ESP_SIMPLE_BOOT=n
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
CONFIG_ESPTOOLPY_FLASHMODE_DIO=y

# Console & Serial
CONFIG_UART_CONSOLE=y
CONFIG_UART_ESP32=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SERIAL_ESP32_USB=y
CONFIG_LOG_BACKEND_UART=y

# Wi-Fi Networking
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y

# WiFi static config via Manager
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.199.123"
CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.199.254"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"

# Sensors
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_BMI160=y
CONFIG_BMI160_TRIGGER_NONE=y

# Peripherals
CONFIG_PWM=y
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_PCNT_ESP32=y

# RMT LED
CONFIG_RMT_TX=y
CONFIG_RMT_TX_ESP32=y
CONFIG_RMT_TX_LOG_LEVEL_DBG=y
CONFIG_RMT_TX_INIT_PRIORITY=80
CONFIG_RMT_TX_CHANNEL_INIT_PRIORITY=90

# MCUboot & OTA Configuration
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_ZCBOR=y
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_UDP=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y

# Remote syslog over UDP (Wi-Fi)
CONFIG_LOG_BACKEND_NET=n
# CONFIG_LOG_BACKEND_NET_SERVER="192.168.199.120:1514"
# CONFIG_LOG_BACKEND_NET_AUTOSTART=y
