# Minimal config for boot troubleshooting
CONFIG_NEWLIB_LIBC=y
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_FPU=n

# Bootloader
CONFIG_ESP_SIMPLE_BOOT=y
CONFIG_HEAP_MEM_POOL_SIZE=2048

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_UART=y

# DISABLE EVERYTHING ELSE
CONFIG_NETWORKING=n
CONFIG_SENSOR=n
CONFIG_I2C=n
CONFIG_PWM=n
CONFIG_GPIO=y
CONFIG_ADC=n
CONFIG_PCNT_ESP32=n
CONFIG_NANOPB=n
