# General config
CONFIG_PICOLIBC=y
CONFIG_CPP=y
CONFIG_STD_CPP20=y

# Bootloader
CONFIG_ESP_SIMPLE_BOOT=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_GPIO=y
