# General config
CONFIG_PICOLIBC=y
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_FPU=n

# Bootloader (Using ESP Simple Boot for C6)
CONFIG_ESP_SIMPLE_BOOT=y
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y
CONFIG_ESPTOOLPY_FLASHMODE_DIO=y
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_IDLE_STACK_SIZE=2048
CONFIG_ISR_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=131072

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_PRINTK=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_CBPRINTF_COMPLETE=y

# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_ESP32=y
CONFIG_PRINTK=y
CONFIG_BOOT_BANNER=y

# Give the USB bridge time
CONFIG_BOOT_DELAY=500

# SERIAL (Internal USB-Serial-JTAG for /dev/ttyACM0)
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SERIAL_ESP32_USB=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_ESP32=y
CONFIG_LOG_BACKEND_UART=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_STATISTICS=y
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME="robot.luca.home.arpa"

# WiFi static config via Manager
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.199.123"
CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.199.254"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"

# Sensors
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_BMI160=y
CONFIG_BMI160_TRIGGER_NONE=y

# Peripherals
CONFIG_PWM=y
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_PCNT_ESP32=y

# RMT LED
CONFIG_RMT_TX=y
CONFIG_RMT_TX_ESP32=y
CONFIG_RMT_TX_LOG_LEVEL_DBG=y
CONFIG_RMT_TX_INIT_PRIORITY=80
CONFIG_RMT_TX_CHANNEL_INIT_PRIORITY=90

# Protobuf (nanopb)
CONFIG_NANOPB=y
